const POSTS = {
  FETCH: "POSTS_FETCH",
  FETCH_SUCCESS: "POSTS_FETCH_SUCCESS",
  FETCH_FAIL: "POSTS_FETCH_FAIL"
}

export { POSTS };

// export const FETCH_POSTS = "FETCH_POSTS";
// export const NEW_POST = "NEW_POST";