const POSTS = {
  FETCH: "POSTS_FETCH",
  FETCH_SUCCESS: "POSTS_FETCH_SUCCESS",
  FETCH_FAIL: "POSTS_FETCH_FAIL"
}

const NEW_POST = {
  CREATE: "NEW_POST_CREATE",
  CREATE_SUCCESS: "NEW_POST_CREATE_SUCCESS",
  CREATE_FAIL: "NEW_POST_CREATE_FAIL"
}

export { POSTS, NEW_POST };
